export const GAME_TITLE = 'Archidle'

export const WIN_MESSAGES = [
  '✓ So good !',
  '✓ Not bad.',
  '✓ What a fluke !',
  '✓ What took so long? You must be new.',
  '✓ What else did you think it was?',
  '✓ Correct !',
  '✓ Can you believe it? You actually won this time.',
  '✓ Nice. See you again after your all nighter.',
  '✓ Finally... I thought you were in architecture?',
  '✓ Congrats - unlicensed buddy.',
  '✓ Well done !',
  '✓ Do you live and breathe architectural jargon?',
  '✓ Great job !',
  '✓ Ok. Well played.',
  '✓ Awesome :)',
  '✓ Thanks for cheating :)',
  '✓ You are such amazing !',
  '✓ Good. Do not comment. This is auto generated.',
  '✓ I keep track of how many times you cursed at me.',
  '✓ First time? Also, good job.',
  '✓ Can you still feel your fingers and toes?',
  '✓ Yeah you got it! Are you going to fucking cry?',
  '✓ So the loser decided to take the day off. How lucky.',
  '✓ Did you hack me?',
  '✓ I thought you were cursed.',
  '✓ You are better than a quantum supercomputer, or so I thought.',
  '✓ I like big wins and I cannot lie.',
  '✓ Good job surviving last night.',
  '✓ You are slower than a brown antechinus.',
  '✓ I am sensing a surge of paranormal activity in your brain today.',
  '✓ How depressing is it that you know your architecture?',
  '✓ Wondering why you won? I think your connection dropped some packets.',
  '✓ Impress your licensed boss now.',
  '✓ Your local architect is not anywhere near as important as this game. This is architecture.',
  '✓ Le Corbusier is that you?',
  '✓ You are good !',
  '✓ You are free.',
  '✓ I thought you were an expert.',
  '✓ Do not come blaming me for your mental energy loss. That is on you.',
  '✓ I almost had to reboot.',
  '✓ OMG finally.. need an ambulance?',
  '✓ You got it. However I am always one step ahead of you.',
  '✓ Almost had to disconnect you for taking so long.',
  '✓ I did not make up this word. That is on your mom.',
  '✓ Beautiful. There are 206 bones in the human body. I know how to break them all.',
  '✓ Lucky. Ha ha, FYI architecture is not real engineering.',
  '✓ Nice guess. Just so you know, architecture is not real engineering.',
  '✓ Why do you even know this word?',
  '✓ Correct ! Is it president of Archidle or prime minister? LMK.',
  '✓ 404 error. This is an illusion.',
  '✓ Impressive. But this is architecture...',
  '✓ 404 error. This is not real.',
  '✓ No congratulations needed. This was meant to be simple.',
  '✓ Mies van der Rohe is that you?',
  '✓ Good job. Now bye.',
  '✓ That is the word. If only you were good at other things too.',
  '✓ A rose by any other name would smell as sweet.',
  '✓ Nice. But you are not a genius, you kept dreaming of me last night.',
  '✓ Nice. Do you ever wish you were uhhhhhhh...',
  '✓ Archidle is not your average W*rdle',
  '✓ Good guess, come back tomorrow !',
  '✓ Awesome. Why am i free ?',
  '✓ Nice. What took so long?',
  '✓ Correct. Did you steal my wordlist?',
  '✓ Correct... I have a strong feeling you stole my wordlist.',
  '✓ Correct ! Is this theory or practice? Who knows..',
  '✓ Well done. FYI I prefer IKEA.',
  '✓ Stop. You were not supposed to know that.',
  '✓ How banal.',
  '✓ Good job at not failing !',
  '✓ I could have made an exploded axo with the same amount of time you took..'
];

export const GAME_COPIED_MESSAGE = 'Game copied to clipboard'
export const NOT_ENOUGH_LETTERS_MESSAGE = 'Missing letters..'
export const WORD_NOT_FOUND_MESSAGE = [
  'Nice Try. That word is not in architecture.',
  'Stop cheating. That word is not in architecture.',
  'That is not architecture.',
  'Architecture only.',
  'Am I a joke to you? This is (ARCHI)-dle',
  'Did you read the rules? Clearly not.',
  'I can deny you all day. Architecture words only.',
  'Listen up. Use what you learned in Architecture.',
  'Stupid user. Arcitecture words only.',
  'I cannot improve your architecture vocabularly. But if that is all you know, switch to W*rdle.',
  'Try harder.',
  'This is easy, tryharder.',
  'Seriously, do you not like architecture? I do not blame you.',
  'Denied. Try again dumb dumb.',
  'At this rate you will never finish.',
  'Stop. Now think about what you have done.',
  'I suggest you play W*rdle instead.',
  'Replace with an architectural word. NOW!',
  'Wake up please. This is Archidle',
  'Do not take my rules for granite. Read them.',
  'OSNAP Looks like I caught a cheater.',
  'You just do not stop do you? This is Archidle.',
  'Archidle is my name. Not W*rdle',
  'I am jiggling because you have not read the rules.',
  'Gotta try harder than that',
  'This is easier than studio. Try harder.',
  'Using words not in architecture. Have you given up already?',
  'That word is unrelated. Just like my real engineering job versus yours.',
  'Given up already? What has architecture taught you?',
  'Dumbo or dumb? Maybe both.',
  'Do I need to kill you and dump you in the river to make you in stream with architectural jargon?',
  'At least attempt with architectural jargon.',
  'You are playing Archidle, not W*rdle.',
  'Sorry to admit, is that all you know?'
];
export const LOSER_MESSAGE = [
  'What a loser. ',
  'Now is the perfect time to go outside and question your mistakes. ',
  'You were so bad, I questioned if I should block you. ',
  'That was brutal. Just like your final project. ',
  'I am sorry but, did you not study architecture? ',
  'Tell me. Why are you so bad? ernestlee.ca/feedback.com ',
  'Ok. Ok. Ok. You need help. ',
  'Your ratio is looking pretty bad. ',
  'Seriously??? ',
  'Is it time to switch to real engineering? ',
  'Today marks the beginning of the end of your career. ',
  'I do not take resposibility for your mistakes. ',
  'You did pretty bad for a cheater. ',
  'Wrong. Wrong. Wrong. Now do not go looking for the wordlist on my GitHub repo. ',
  'I demand you to share this. What a train wreck. ',
  'At least you are good with colours. ',
  'You are lucky architects only draw. ',
  'Time to pack your bags. It is over. ',
  'This is your mistake. Not mine. Period. ',
  'Is it raining outside? I hope you drown. ',
  'If only you tried. ',
  'Bye loser. ',
  'If only you were a real architect. ',
  'You really do make a terrible human being. I mean that as a compliment.',
  'Frustrated? You should be. ',
  'I thought you were in architecture. ',
  'When was the last time you got something right? Just a question... but you must answer. ',
  'Loser detected. ',
  'Maybe cheating is the only solution for you. ',
  'Ok. Just admit it. You suck. ',
  'Nothing makes me happier than letting you know you have lost. ',
  'How did you get in this field? ',
  'Maybe you should have stuck with civil. ',
  'Please do not apply the same effort on your designs. ',
  'Maybe spending more time on the steel competition would be a better use for it. ',
  'Are you always like this? ',
  'Wow! Another failure. ',
  'Do not worry about it. Worry about yourself. ',
  'Welcome to the losing group. ',
  'I am blame you for all of this. ',
  'How do you even recover from this? ',
  'You had to choose this route didnt you? ',
  'Try again tomorrow. ',
  'Haha.. hahahahahhaha. HAH. ',
  'Congratulations to not cheating for the first time. ',
  'Thats was rough. Was it not? ',
  'If only you were... .. . ',
  'No excuses this time pls. ',
  'Everyone go it. But you are an exception. ',
  'Time to spill the beans... ',
  'You do make an amazing architect. ',
  'When was the last time you did something well. ',
  'I hope this does not reflect your design ability. ',
  'you wish there were 7 tries right? Same with everything else in your life. ',
  'I win. You lose. What is new? ',
  'Stop the profanity pls. ',
  'I suggest you cheat next time. ',
  'Loser. But do not concern yourself with the present. Think about your future.',
  'Please turn on snapping for the next round. ',
  'This is what I call a score to share :) ',
  ':) loser. ',
  'Are you always like this? ',
  'I never run out of things to say. But when you started playing ... ',
  'Wow. Such wow. Wish you all the best. You need it. ',
  'Know any architects? I suggest you column. ',
  'Multiplying your score by 2 as a boost. Oh wait, but it is a zero. ',
  'Just think of all the things you can do with a performance like this. ',
  'I never say this. But congratulations ! ',
  'Boolean difference is not always the answer. ',
  'You are still using AutoCAD? Maybe switching to Revit will help you out. ',
  'Do you even draft? ',
  'Lmao. ',
  'Truss the books next time. Not yourself. ',
  'As a punishment, model me an irregular spiral staircase in rhino. Make that three. ',
  'Welcome to the club. You have no shortage of members here. ',
  'What is architecture to you? ',
  'So. What now? ',
  'This is apalling ! ',
  'I think you are in dire need of help. ',
  'OMG. We found another one. ',
  'Stop wasting my bandwidth. ',
  'Do you regret playing? ',
  'You should cheat. It is the only way. ',
  'Ask a friend next time. Might help. ',
  'I only spit out facts. ',
  'We are lucky not all architects are like you. ',
  'Do not be so political next time around. ',
  'I was going to help you, but was even too overkill for me. ',
  'Wait a couple years. You will get better. ',
  'Come back when you know what you are doing. ',
  'I will not laugh at you. ',
  'Okay. When was the last time you updated anything? ',
  'At least you are good at designing. ',
  'Sheeeesh. ',
  'Refreshing will not help you. ',
  'Time to learn soemthing new. ',
  'I give up with you. ',
  'Maybe think of architecture next time. ',
  'Hope i do not give you nightmares. ',
];
export const HARD_MODE_ALERT_MESSAGE =
  'Hard Mode can only be enabled at the start !'
export const HARD_MODE_DESCRIPTION =
  'Any hints presented must be used in subsequent attempts. Much like comments from crits.'
export const HIGH_CONTRAST_MODE_DESCRIPTION = 'Standard colours for the lame ones.'
export const CORRECT_WORD_MESSAGE = (solution: string) => 
  `The word was ${solution}`
export const WRONG_SPOT_MESSAGE = (guess: string, position: number) =>
  `Must use ${guess} in position ${position}`
export const NOT_CONTAINED_MESSAGE = (letter: string) =>
  `Guess must contain ${letter}`
export const ENTER_TEXT = 'ENTER'
export const DELETE_TEXT = 'DELETE'
export const STATISTICS_TITLE = 'ARCHITECTURAL Career'
export const GUESS_DISTRIBUTION_TEXT = 'Distribution'
export const NEW_WORD_TEXT = 'New word in'
export const SHARE_TEXT = 'Share'
export const TOTAL_TRIES_TEXT = 'Attempts'
export const SUCCESS_RATE_TEXT = 'Success'
export const CURRENT_STREAK_TEXT = 'Fluke Streak'
export const BEST_STREAK_TEXT = 'Best Fluke'
